
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html#appspec-reference-lambda
version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "notify_user"
        Alias: "notify_user_alias"
        CurrentVersion: "$LATEST"
        TargetVersion: "$LATEST"